import { StopwatchProvider } from "../context/stopWatchContext";
import { UserProvider } from "../context/userContext";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "../components/uiComponents/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Playstation management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <StopwatchProvider> */}
        <UserProvider>
          <>
            <Navbar />
            <main className="main-cont">{children}</main>
          </>
        </UserProvider>
        {/* </StopwatchProvider> */}
      </body>
    </html>
  );
}
